name: base_cod_view
description: " A Flutter package for displaying and highlighting code with customizable styles and features."
version: 0.0.5
homepage: "https://github.com/SwanFlutter/base_code-view.git"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


